### ISSUE TITLE
Tileset enhancement: allow to shift position of several tiles at the same time

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus-quest-editor#249] opened 2016-11-16 01:02 UTC
Allow to shift position of several tiles at the same time in the tileset editor:
In the tileset editor we can shift the position (coordinates) of one tile with drag and drop, but this is not possible when several tiles are selected at the same time.

This will make our lives easier when developping new tilesets, when we add new tiles and we need to rearrange the position of the old ones.

**Comment by christopho** [comment] 2016-11-16 07:56
Duplicate of #171.

**Closed by christopho** 2016-11-16 07:56 UTC

**Comment by Diarandor** [comment] 2016-11-16 09:27
Whoops, sorry. I did not see it.
