### ISSUE TITLE
Bug: tile properties not updated after overwritting tileset

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus-quest-editor#250] opened 2016-11-16 02:13 UTC
Bug: tile properties not updated after overwritting tileset.

To reproduce the bug, do the following:
1) Replace the tileset png file while the tileset is open in the editor.
2) The editor will ask if you want to reload the file for the tileset. Click in "yes".
3) Click in other tiles different from the one that is already selected. Then, the properties will not be updated (the ones of the previous tile will not change); you can click in other tiles several times, but that does not change the properties, and you are forced to close and reopen that tileset (because there is no refresh/update button).

**Comment by christopho** [comment] 2016-11-16 07:53
Duplicate of #218. Already fixed, planned for 1.5.1.

**Closed by christopho** 2016-11-16 07:53 UTC
Labels: bug
